CREATE OR REPLACE TABLE `{{ params.dwh_dataset }}.D_TIME` AS
SELECT DISTINCT
  ARRIVAL_DATE DATE,
  CAST(DAY(ARRIVAL_DATE) AS NUMERIC) DAY,
  CAST(MONTH(ARRIVAL_DATE) AS NUMERIC) MONTH,
  CAST(YEAR(ARRIVAL_DATE) AS NUMERIC) YEAR,
  CAST(QUARTER(ARRIVAL_DATE) AS NUMERIC) QUARTER,
  CAST(DAYOFWEEK(ARRIVAL_DATE) AS NUMERIC) DAYOFWEEK,
  CAST(WEEKOFYEAR(ARRIVAL_DATE) AS NUMERIC) WEEKOFYEAR

FROM
  `{{ params.project_id }}.{{ params.dwh_dataset }}.F_IMMIGRATION_DATA`
